<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="camera_macro" params="prefix parent xyz rpy">
        <xacro:include filename="$(find hippo_sim)/models/common/urdf/common.xacro" />
        <xacro:include filename="$(find hippo_sim)/models/camera/urdf/camera_params.xacro" />
        <xacro:property name="link" value="$(arg vehicle_name)/${prefix}_link" />
        <xacro:property name="joint" value="$(arg vehicle_name)/${prefix}_joint" />

        <link name="${link}">
            <xacro:zero_inertia />
            <visual>
                <origin rpy="0 ${radians(90)} 0" />
                <geometry>
                    <cylinder radius="0.02" length="0.01" />
                </geometry>
            </visual>
        </link>

        <joint name="${joint}" type="fixed">
            <origin xyz="${xyz}" rpy="${rpy}" />
            <parent link="${parent}" />
            <child link="${link}" />
        </joint>
        <gazebo reference="${link}">
            <disableFixedJointLumping>true</disableFixedJointLumping>
            <preserveFixedJoint>true</preserveFixedJoint>
        </gazebo>

        <gazebo reference="${link}">
            <visual>
                <material>
                    <ambient>0.5 0.25 1 1</ambient>
                    <diffuse>1 0.5 1 1</diffuse>
                    <specular>1 1 1 1</specular>
                </material>
            </visual>
            <sensor name="$(arg vehicle_name)_${prefix}" type="camera">
                <camera>
                    <camera_info_topic>$(arg vehicle_name)/${prefix}/camera_info</camera_info_topic>
                    <horizontal_fov>${horizontal_fov}</horizontal_fov>
                    <image>
                        <width>${width}</width>
                        <height>${height}</height>
                    </image>
                    <clip>
                        <near>0.05</near>
                        <far>10</far>
                    </clip>
                    <lens>
                        <intrinsics>
                         <fx>${width/2.0/tan(horizontal_fov/2.0)}</fx>
                         <fy>${width/2.0/tan(horizontal_fov/2.0)}</fy>
                         <cx>${width/2.0}</cx>
                         <cy>${height/2.0}</cy>
                         <s>0</s>
                        </intrinsics>
                    </lens>
                </camera>
                <always_on>1</always_on>
                <update_rate>${fps}</update_rate>
                <visualize>true</visualize>
                <topic>$(arg vehicle_name)/${prefix}/image_rect</topic>
                <!-- needs to be changed to gz_frame_id in the future -->
                <ignition_frame_id>$(arg vehicle_name)::${prefix}</ignition_frame_id>
            </sensor>
        </gazebo>

    </xacro:macro>
</robot>
